### ISSUE TITLE
Error in generating RDF Molecules for two SPARQL endpoints

### ISSUE THREAD

**Issue by code8git** [SDM-TIB/Ontario#5]
Hi,

I am trying to run the script "create_rdfmts.py" for creating RDF molecules for two example rdf datasets hosted using two SPARQL endpoint but throws the below exception:

RDFLib Version: 5.0.0
Finding inter-links between: DrugBank  and  KEGG  ....
==============================//=========//===============================
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 98, in get_links
    reslist = get_external_links(endpoint1, c['rootType'], p['predicate'], endpoint2, rdfmt2)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 125, in get_external_links
    res, card = contactRDFSource(query_copy, referer)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 453, in contactRDFSource
    (server, path) = server.split("/", 1)
ValueError: not enough values to unpack (expected 2, got 1)
RDFLib Version: 5.0.0
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 98, in get_links
    reslist = get_external_links(endpoint1, c['rootType'], p['predicate'], endpoint2, rdfmt2)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 125, in get_external_links
    res, card = contactRDFSource(query_copy, referer)
  File "D:\code\python\ontario\scripts\create_rdfmts.py", line 453, in contactRDFSource
    (server, path) = server.split("/", 1)
ValueError: not enough values to unpack (expected 2, got 1)

 

Thanks & Regards.

**Comment by prohde** [comment]
Hi,

could you please provide the URLs you are using in Ontario's configuration?

**Comment by code8git** [comment]
Hi,

Thank you for the prompt reply.

Below are the URLs used in the configuration:

http://localhost:8890/sparql
http://localhost:8891/sparql

Thanks.

**Comment by prohde** [comment]
Sorry for the late reply. I just pushed the fix to your issue.
